[tool.poetry]
name = "cardiac-arrest"
version = "0.1.0"
description = "ECG classification app"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
tensorflow = "2.13.0"
fastapi = "0.120.0"
uvicorn = "0.38.0"
numpy = ">=2.1.0"
pillow = "11.0.0"
python-multipart = "0.0.9"
protobuf = ">=5.28.0"
pydantic = "2.9.2"
pydantic-core = "2.23.4"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
